#ansible -m copy -a "dest=hello content=world" localhost --check --diff
#

- name: copy module test
  hosts: localhost
  tasks:
  - copy: 
      dest: hello 
      content: world
  - command: date

- name: Ansible Control Node Installs 
  become: yes
  hosts: localhost
  tasks:
  - apt:
      name: python3-argcomplete
      state: present
  - apt: 
       name: ansible-lint
       state: present

